#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Text-Reform
Version  : 1.20
Release  : 1
URL      : http://search.cpan.org/CPAN/authors/id/C/CH/CHORNY/Text-Reform-1.20.tar.gz
Source0  : http://search.cpan.org/CPAN/authors/id/C/CH/CHORNY/Text-Reform-1.20.tar.gz
Summary  : Manual text wrapping and reformatting
Group    : Development/Tools
License  : Artistic-1.0-Perl
Requires: perl-Text-Reform-doc

%description
Text::Reform version 1.20
NAME
Text::Reform - Manual text wrapping and reformating

%package doc
Summary: doc components for the perl-Text-Reform package.
Group: Documentation

%description doc
doc components for the perl-Text-Reform package.


%prep
%setup -q -n Text-Reform-1.20

%build
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make V=1  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.22.0/Text/Reform.pm

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man3/*
